#!/usr/bin/env python3
"""
generate_cses.py

Scan folders under a root (default: programming/cses) where each folder is named
"<id>_<Problem Name>" and generate a static `CSES.html` file listing each entry
with links to `problem.pdf`, `solution.cpp` and `explained.pdf` when present.

Usage:
    python scripts/generate_cses.py
    python scripts/generate_cses.py --root programming/cses --output CSES.html

The script produces relative links in the generated HTML, URL-escaping path components.
"""
from __future__ import annotations
import os
import sys
import argparse
import html
import urllib.parse
from typing import List, Optional, Tuple


def parse_folder_name(folder: str) -> Tuple[Optional[int], str]:
    """Return (id, name) parsed from a folder like '1_Weird Algorithm'.
    If id cannot be parsed, id is None and name is the original folder string (underscores replaced).
    """
    if '_' in folder:
        left, right = folder.split('_', 1)
        try:
            return int(left), right.replace('_', ' ')
        except ValueError:
            pass
    # fallback
    return None, folder.replace('_', ' ')


def url_for(path: str, output_path: str) -> str:
    """Return an HTML-safe relative URL from output_path to path, with each component URL-encoded."""
    rel = os.path.relpath(path, os.path.dirname(os.path.abspath(output_path)))
    parts = rel.split(os.sep)
    quoted = '/'.join(urllib.parse.quote(part) for part in parts)
    return quoted


def find_entries(root: str) -> List[dict]:
    root = os.path.abspath(root)
    entries = []
    if not os.path.isdir(root):
        return entries

    for name in os.listdir(root):
        folder_path = os.path.join(root, name)
        if not os.path.isdir(folder_path):
            continue

        id_val, display_name = parse_folder_name(name)

        # Expected files
        problem = os.path.join(folder_path, 'problem.pdf')
        explained = os.path.join(folder_path, 'explained.pdf')
        solution = os.path.join(folder_path, 'solution.cpp')

        # If solution.cpp isn't present, optionally pick any .cpp in the folder
        if not os.path.exists(solution):
            for f in os.listdir(folder_path):
                if f.lower().endswith('.cpp'):
                    solution = os.path.join(folder_path, f)
                    break
        if not os.path.exists(problem):
            problem = None
        if not os.path.exists(explained):
            explained = None
        if not os.path.exists(solution):
            solution = None

        entries.append({
            'id': id_val,
            'folder': name,
            'name': display_name,
            'problem': problem,
            'solution': solution,
            'explained': explained,
        })

    # Sort: numeric ids first ascending, then items without numeric id by name
    def sort_key(e):
        return (0, e['id']) if e['id'] is not None else (1, e['name'].lower())

    entries.sort(key=sort_key)
    return entries


def generate_html(entries: List[dict], output_path: str, css_path: Optional[str] = 'css/styles.css') -> str:
    # Basic page header
    css_link = ''
    if css_path:
        css_rel = url_for(os.path.abspath(css_path), output_path) if os.path.exists(css_path) else css_path
        css_link = f'<link rel="stylesheet" href="{css_rel}">'

    head = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CSES Problems</title>
    {css_link}
</head>
<body>
    <nav class="navbar">
        <a href="index.html">MyProjects</a>
        <div>
            <a href="index.html">Home</a>
            <a href="contact.html">Contact</a>
        </div>
    </nav>

    <div class="content" style="max-width:1200px;margin:40px auto;">
        <h1>CSES Problems</h1>
        <p style="color:#666">This file was generated by <code>scripts/generate_cses.py</code>. To regenerate, run the script.</p>
        <table style="width:100%;border-collapse:collapse">
            <thead>
                <tr style="text-align:left;border-bottom:2px solid #ddd">
                    <th style="width:6%;padding:8px">ID</th>
                    <th style="width:44%;padding:8px">Name</th>
                    <th style="width:16%;padding:8px">Problem</th>
                    <th style="width:17%;padding:8px">Solution</th>
                    <th style="width:17%;padding:8px">Explanation</th>
                </tr>
            </thead>
            <tbody>
"""

    rows = []
    for e in entries:
        id_cell = str(e['id']) if e['id'] is not None else ''
        name_cell = html.escape(e['name'])

        def cell_link(path, label):
            if not path:
                return '<span style="color:#999">-</span>'
            href = url_for(path, output_path)
            return f'<a href="{href}" target="_blank" rel="noopener">{html.escape(label)}</a>'

        prob_html = cell_link(e['problem'], 'problem.pdf')
        sol_html = cell_link(e['solution'], os.path.basename(e['solution']) if e['solution'] else 'solution.cpp')
        exp_html = cell_link(e['explained'], 'explained.pdf')

        row = f"""                <tr style=\"border-bottom:1px solid #eee\">
                    <td style=\"padding:8px;vertical-align:middle;text-align:center\">{id_cell}</td>
                    <td style=\"padding:8px;vertical-align:middle\">{name_cell}</td>
                    <td style=\"padding:8px;vertical-align:middle;text-align:center\">{prob_html}</td>
                    <td style=\"padding:8px;vertical-align:middle;text-align:center\">{sol_html}</td>
                    <td style=\"padding:8px;vertical-align:middle;text-align:center\">{exp_html}</td>
                </tr>\n"""
        rows.append(row)

    body = '\n'.join(rows)

    foot = """
            </tbody>
        </table>
    </div>
</body>
</html>
"""

    return head + body + foot


def main(argv: List[str]):
    parser = argparse.ArgumentParser(description='Generate CSES.html from a folder of problems')
    parser.add_argument('--root', '-r', default='programming/cses', help='Root folder containing problem folders')
    parser.add_argument('--output', '-o', default='CSES.html', help='Output HTML file to write')
    parser.add_argument('--css', default='css/styles.css', help='Path to site CSS (optional)')
    args = parser.parse_args(argv)

    entries = find_entries(args.root)
    html_text = generate_html(entries, args.output, css_path=args.css)

    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(html_text)

    print(f'Wrote {len(entries)} entries to {args.output}')


if __name__ == '__main__':
    main(sys.argv[1:])
